#ifndef VEHICLE_CONFIG_H
#define VEHICLE_CONFIG_H

/* Fixed vehicle geometry and mission limits (SI units). */
#define VEHICLE_WHEELBASE_M                 (0.680f)
#define VEHICLE_FRONT_TRACK_M               (0.590f)
#define VEHICLE_REAR_TRACK_M                (0.585f)
#define RECORD_MAX_DISTANCE_M               (100.0f)
#define RECORD_MAX_TIME_S                   (120.0f)
#define REPLAY_MAX_SPEED_MPS                (2.0f)
#define PATH_PERSISTENCE_ENABLE             (0)
#define GPS_ENABLE                          (0)
#define MAG_FUSION_ENABLE                   (0)

/* Static storage and path processing. */
#define PATH_MAX_POINTS                     (4096U)
#define PATH_POINT_SIZE_BYTES               (24U)
#define PATH_STORAGE_BYTES                  (PATH_MAX_POINTS * PATH_POINT_SIZE_BYTES)
#define PATH_RECORD_SPACING_M               (0.025f)
#define PATH_RESAMPLE_SPACING_M             (0.030f)
#define PATH_MIN_POINT_DISTANCE_M           (0.002f)
#define PATH_YAW_SAMPLE_THRESHOLD_RAD       (0.035f)
#define PATH_MAX_INPUT_SEGMENT_M            (0.150f)
#define PATH_MAX_YAW_JUMP_RAD               (0.80f)
#define PATH_MIN_VALID_POINTS               (8U)
#define PATH_MIN_VALID_LENGTH_M             (0.20f)
#define PATH_SMOOTH_HALF_WINDOW             (2U)
#define PATH_CURVATURE_WINDOW               (4U)

/* Cooperative scheduler periods. */
#define VEHICLE_FAST_PERIOD_US              (1000ULL)
#define VEHICLE_CONTROL_PERIOD_US           (5000ULL)
#define VEHICLE_ESTIMATOR_PERIOD_US         (5000ULL)
#define VEHICLE_TRACKER_PERIOD_US           (10000ULL)
#define VEHICLE_LOG_PERIOD_US               (20000ULL)
#define VEHICLE_DISPLAY_PERIOD_US           (100000ULL)
#define VEHICLE_COMMAND_TIMEOUT_US          (150000ULL)
#define VEHICLE_CONTROL_TIMEOUT_US          (30000ULL)
#define VEHICLE_SENSOR_TIMEOUT_US           (50000ULL)

/* Sensor validation and estimator tuning. */
#define IMU_CALIBRATION_TIME_S              (3.0f)
#define IMU_CALIBRATION_MIN_SAMPLES         (400U)
#define IMU_CALIBRATION_MAX_GYRO_RADPS      (0.12f)
#define IMU_CALIBRATION_MAX_ACCEL_DELTA_MPS2 (1.5f)
#define IMU_MAX_ACCEL_MPS2                  (100.0f)
#define IMU_MAX_GYRO_RADPS                  (35.0f)
#define IMU_BIAS_STATIONARY_GAIN            (0.003f)
#define IMU_BIAS_MOVING_GAIN                (0.00015f)
#define LOCALIZATION_SPEED_FILTER_GAIN      (0.30f)
#define LOCALIZATION_WHEEL_OMEGA_GAIN       (0.10f)
#define LOCALIZATION_STEER_OMEGA_GAIN       (0.05f)
#define LOCALIZATION_STATIC_SPEED_MPS       (0.025f)
#define LOCALIZATION_STATIC_GYRO_RADPS      (0.04f)
#define LOCALIZATION_OMEGA_DISAGREE_RADPS   (0.80f)
#define LOCALIZATION_SLIP_SPEED_MPS         (0.80f)
#define LOCALIZATION_MIN_DT_S               (0.0005f)
#define LOCALIZATION_MAX_DT_S               (0.050f)
#define ENCODER_MAX_ABS_SPEED_MPS           (3.50f)
#define ENCODER_MAX_ACCEL_MPS2              (20.0f)

/* Rear wheel speed control. */
#define WHEEL_SPEED_KP                      (0.22f)
#define WHEEL_SPEED_KI                      (0.75f)
#define WHEEL_SPEED_FEEDFORWARD             (0.18f)
#define WHEEL_SPEED_INTEGRAL_LIMIT          (0.35f)
#define WHEEL_SPEED_OUTPUT_LIMIT            (0.80f)
#define WHEEL_SPEED_OUTPUT_SLEW_PER_S       (3.0f)
#define WHEEL_SPEED_ZERO_BAND_MPS           (0.025f)
#define WHEEL_SPEED_DIRECTION_HOLD_S        (0.08f)

/* Steering position control. */
#define STEERING_KP                         (1.80f)
#define STEERING_KI                         (0.40f)
#define STEERING_KD                         (0.050f)
#define STEERING_INTEGRAL_LIMIT             (0.25f)
#define STEERING_OUTPUT_LIMIT               (0.55f)
#define STEERING_OUTPUT_SLEW_PER_S          (2.5f)
#define STEERING_POSITION_DEADBAND_RAD      (0.006f)
#define STEERING_STALL_DUTY                 (0.18f)
#define STEERING_STALL_COUNT_DELTA           (2LL)
#define STEERING_STALL_TIMEOUT_S            (0.80f)

/* Stage-one guarded command limits. */
#define STAGE1_MAX_SPEED_MPS                (2.0f)
#define STAGE1_MAX_STEERING_RAD             (0.70f)
#define STAGE1_STOP_DISTANCE_MARGIN_M       (0.15f)
#define STAGE1_STOP_TIME_MARGIN_S           (0.30f)
#define CALIBRATION_TEST_MAX_DUTY           (0.12f)
#define CALIBRATION_TEST_MAX_TIME_S         (2.0f)
#define CALIBRATION_TEST_MAX_SPEED_MPS      (0.30f)

/* Reverse path tracking. */
#define REVERSE_NOMINAL_SPEED_MPS           (-0.80f)
#define REVERSE_LOOKAHEAD_MIN_M             (0.22f)
#define REVERSE_LOOKAHEAD_MAX_M             (0.90f)
#define REVERSE_LOOKAHEAD_TIME_S            (0.40f)
#define REVERSE_CURVATURE_SPEED_GAIN        (1.8f)
#define REVERSE_CROSSTRACK_SPEED_GAIN       (0.9f)
#define REVERSE_CROSSTRACK_GAIN             (0.80f)
#define REVERSE_HEADING_GAIN                (0.65f)
#define REVERSE_CURVATURE_FEEDFORWARD_GAIN  (1.0f)
#define REVERSE_MAX_STEERING_RAD            (0.70f)
#define REVERSE_ACCEL_LIMIT_MPS2            (0.70f)
#define REVERSE_DECEL_LIMIT_MPS2            (1.00f)
#define REVERSE_TERMINAL_DECEL_DISTANCE_M   (1.50f)
#define REVERSE_FINISH_DISTANCE_M           (0.12f)
#define REVERSE_FINISH_SPEED_MPS            (0.08f)
#define REVERSE_SEARCH_BACK_POINTS          (8U)
#define REVERSE_SEARCH_FORWARD_POINTS       (80U)
#define REVERSE_INDEX_LOSS_LIMIT            (20U)
#define REVERSE_MAX_CROSSTRACK_ERROR_M       (0.90f)
#define REVERSE_MAX_HEADING_ERROR_RAD       (1.20f)

/* Safety monitoring. */
#define MOTOR_STALL_DUTY                    (0.25f)
#define MOTOR_STALL_SPEED_MPS               (0.025f)
#define MOTOR_STALL_TIMEOUT_S               (0.80f)
#define VEHICLE_CONTROLLED_STOP_TIMEOUT_US  (3000000ULL)
#define WHEEL_MISMATCH_MIN_SPEED_MPS        (0.25f)
#define WHEEL_MISMATCH_MAX_MPS              (1.20f)
#define WHEEL_MISMATCH_TIMEOUT_S            (0.60f)
#define MT6701_MAX_DELTA_COUNT_PER_SAMPLE   (4096)
#define MT6701_ERROR_LIMIT                  (5U)

/* Fixed ring buffers. */
#define VEHICLE_LOG_BUFFER_SIZE             (16384U)
#define VEHICLE_COMMAND_BUFFER_SIZE         (192U)
#define VEHICLE_CSV_LINE_SIZE               (512U)

#endif
